export default en = {
  Name: "English",
  ChangeLanguage: "Change Language",
  Hello: "Welcome! Our products are made of first class fabrics.",
  Country: "Country",
  Login: "Login",
  Continue: "Continue",
  Email: "Email",
  Password: "Password",
  PasswordRt: "Password Again",
  Register: "Register",
  NameSurname: "Name-Surname",
  NavigateLogin: "Return to login screen",
  HomeScreen: "Home Screen",
  Products: "Products",
  MyBag: "My Bag",
  Contact: "Contact Us",
  Share: "Share The App",
  Logout: "Logout",
  Subject: "Subject",
  Send: "Send",
  ContactUs: "To contact us, fill out and send the form below.",
  Error: "Error!",
  EmailError: "Please enter a valid email address.",
  FieldError: "Please fill in all fields.",
  Ok: "Ok",
  EmailProblem: "There is already a problem registered with the Email address you entered.",
  Congratulations: "Congratulations!",
  CreateProblem: "Your request has been successfully created, please wait for a response :)",
  WaitingApproval: "Waiting For Approval",
  WaitingAdminApproval: "Your account is waiting for admin approval. Once approved, you will be able to log in.",
  WrongPassword: "Wrong Password",
  WrongPasswordAlert: "You entered the password incorrectly. Please try again.",
  UserNotFound: "User Not Found",
  UserNotFoundAlert: "No user was found for the e-mail address you entered. Please register.",
  SameEmail: "There is already a user connected to the email address you entered.",
  PasswordMatch: "Passwords do not match",
  PasswordMatchError: "The passwords you entered do not match each other.",
  More: "More",
  NewProducts: "New Products",
  PopularProducts: "Popular Products",
  AddToCart:"Add To Cart",
  SendWhatsapp:"Send Via Whatsapp",
  Pieces:"Pieces",
  gomlek: 'Shirt',
  mont: 'Coat',
  pantolon: 'Trousers',
  bluz: 'Blouse',
  esofman: 'Tracksuit',
  sweatshirt: 'Sweatshirt',
  tshirt: 'T-shirt',
  elbise: 'Dress',
  description:'Our products are 100% cotton',
  ustgiyim:'Top Wear',
  altgiyim:'Bottom Wear',
  quantityInCart:'Quantity in Cart',
  pieces:'Piece',
  all:'All',
  etek:'Skirt',
  Settings: "Settings",
  Sorry: "Sorry",
  NotLogin: "You cannot use this feature because you are not logged in.",
  NavigateHome: "Continue without logging in",
  SendOrder:"Send To Buy",
  OrderSended:'Your order has been successfully delivered to the seller. The seller will contact you at the phone number +90 5373673069.',
  WorkingHour:"Our Working Hours 8.30-19.00 UTC+3",
  priceDescription:"*Our product prices may vary depending on the quantity purchased, the shipping process, and other factors.*",
  OrderDetail:"Order Details",
  Order:"Get a Quote",
  ConfirmCart:"Confirm Cart",
  CartEmpty:"Your cart is empty, please add products!",
  OrderInfo:"Product prices may vary depending on the delivery location, the total quantity purchased, and the shipping process. After placing the order, you will be contacted via email and mobile number for further information.",
  Confirm:"Confirm",
  Decline:"Decline",
  SureOrder:"Do you want to confirm the cart?",
  SurOrderAlt:"If you click the 'Confirm' button, your order will be submitted to the seller and processed.",
  Delete:'Your account will be permanently deleted. Are you sure?',
  DeletePermanent:'You may need to register again.',
  OrderHistory: "My Orders",
  new: "New",
  cancelled: "Cancelled",
  pending: "Pending",
  completed: "Completed",
  Status: "Status",
  OrderDate: "Order Date",
  TotalSeries: "Total Series",
  TotalPieces: "Total Pieces",
  DeletedPermanently: "Your account has been deleted permanently."

};