export default pl = {
  Name: "dialekt",
  ChangeLanguage: "Zmień język",
  Hello: "Powitanie! Nasze produkty wykonane są z tkanin najwyższej klasy.",
  Country: "Kraj",
  Login: "Zaloguj sie",
  Continue: "Kontynuować",
  Email: "E-mail",
  Password: "Hasło",
  PasswordRt: "Hasło ponownie",
  Register: "Rejestr",
  NameSurname: "Imię Nazwisko",
  NavigateLogin: "Wróć do ekranu logowania",
  HomeScreen: "Ekran główny",
  Products: "Produkty",
  MyBag: "Moja torba",
  Contact: "Skontaktuj się z nami",
  Share: "Udostępnij aplikację",
  Logout: "Wyloguj",
  Subject: "Temat",
  Send: "Wysłać",
  ContactUs: "Aby się z nami skontaktować wypełnij i wyślij poniższy formularz.",
  Error: "Błąd!",
  EmailError: "Proszę wpisać aktualny adres e-mail.",
  FieldError: "Proszę wypełnić wszystkie pola.",
  Ok: "OK",
  EmailProblem: "Wystąpił już problem związany z wprowadzonym adresem e-mail.",
  Congratulations: "Gratulacje!",
  CreateProblem: "Twoje zapytanie zostało pomyślnie utworzone, poczekaj na odpowiedź :)",
  WaitingApproval: "Czeka na zatwierdzenie",
  WaitingAdminApproval: "Twoje konto czeka na zatwierdzenie przez administratora. Po zatwierdzeniu będziesz mógł się zalogować.",
  WrongPassword: "Złe hasło",
  WrongPasswordAlert: "Wpisałeś hasło niepoprawnie. Proszę spróbuj ponownie.",
  UserNotFound: "Użytkownik nie znaleziony",
  UserNotFoundAlert: "Nie znaleziono użytkownika dla wprowadzonego adresu e-mail. Proszę zarejestruj się.",
  SameEmail: "Z podanym adresem e-mail jest już połączony użytkownik.",
  PasswordMatch: "Hasła nie pasują do siebie",
  PasswordMatchError: "Wprowadzone hasła nie są ze sobą zgodne.",
  More:"Więcej",
  NewProducts:"Nowe Produkty",
  PopularProducts:"Popularne Produkty",
  AddToCart:"Dodaj do koszyka",
  SendWhatsapp:"Wyślij przez Whatsapp",
  Pieces:"Sztuki",
  gomlek: 'Koszula',
  mont: 'Płaszcz',
  pantolon: 'Spodnie',
  bluz: 'Bluza',
  esofman: 'Dres',
  sweatshirt: 'Podkoszulek',
  tshirt: 'Tshirt',
  elbise: 'Sukienka',
  description:'Nasze produkty to 100% bawełna',
  ustgiyim:'Najfatalniejszy',
  altgiyim:'Dolne zużycie',
  quantityInCart:'Ilość w koszyku',
  pieces:'sztuki',
  all:'Wszystko',
  etek:'Spódnica',
  Settings: "Ustawienia",
  Sorry: "Przykro mi",
  NotLogin: "Nie możesz używać tej funkcji, ponieważ nie jesteś zalogowany.",
  NavigateHome: "Kontynuuj bez logowania",
  OrderSended: "Twoje zamówienie zostało pomyślnie dostarczone do sprzedawcy. Sprzedawca skontaktuje się z Tobą pod numerem +90 5373673069.",
  SendOrder: "Z wyjątkiem wyskakującego okienka",
  WorkingHour:"Nasze godziny pracy 8.30-19.00 UTC+3",
  priceDescription:"*Ceny naszych produktów mogą się różnić w zależności od ilości zakupionego towaru, procesu dostawy i innych czynników.*",
  OrderDetail:"Szczegóły zamówienia",
  Order:"Otrzymaj ofertę",
  ConfirmCart:"Potwierdź koszyk",
  CartEmpty:"Twój koszyk jest pusty, prosimy dodaj produkty!",
  OrderInfo:"Ceny produktów mogą się różnić w zależności od lokalizacji dostawy, łącznej ilości zakupionego towaru i procesu dostawy. Po złożeniu zamówienia zostaniesz skontaktowany mailowo i telefonicznie, aby dostarczyć informacje.",
  Confirm:"Potwierdź",
  Decline:"Odrzuć",
  SureOrder:"Czy na pewno chcesz potwierdzić koszyk?",
  SurOrderAlt:"Po kliknięciu przycisku 'Potwierdź', Twoje zamówienie zostanie przesłane do sprzedawcy i przetworzone.",
  Delete:'Twoje konto zostanie trwale usunięte. Jesteś pewien?',
  DeletePermanent:'Być może będziesz musiał się zarejestrować ponownie.',
  OrderHistory: "Moje zamówienia",
  new: "Nowe",
  cancelled: "Anulowane",
  pending: "Oczekujące",
  completed: "Zakończone",
  Status: "Status",
  OrderDate: "Data zamówienia",
  TotalSeries: "Całkowita liczba serii",
  TotalPieces: "Całkowita liczba sztuk",
  DeletedPermanently: "Twoje konto zostało trwale usunięte.",
  
};
