export default ro = {
  Name: "Română",
  ChangeLanguage: "Schimbați limba",
  Hello: "Bine ati venit! Produsele noastre sunt realizate din țesături de primă clasă.",
  Country: "Țară",
  Login: "Autentificare",
  Continue: "Continua",
  Email: "E-mail",
  Password: "Parola",
  PasswordRt: "Reindroduce-ti parola",
  Register: "Inregistreaza-te",
  NameSurname: "Nume Prenume",
  NavigateLogin: "Reveniți la ecranul de conectare",
  HomeScreen: "Ecranul de start",
  Products: "Produse",
  MyBag: "Coșul meu",
  Contact: "Contactaţi-ne",
  Share: "Partajați aplicația",
  Logout: "Deconectare",
  Subject: "Subiect",
  Send: "Trimite",
  ContactUs: "Pentru a ne contacta, completați și trimiteți formularul de mai jos.",
  Error: "Eroare!",
  EmailError: "Vă rugăm să introduceți o adresă de email validă.",
  FieldError: "Vă rugăm să completați toate câmpurile.",
  Ok: "Bine",
  EmailProblem: "Există deja o problemă înregistrată cu adresa de e-mail pe care ați introdus-o.",
  Congratulations: "Felicitări!",
  CreateProblem: "Solicitarea dvs. a fost creată cu succes, vă rugăm să așteptați un răspuns :)",
  WaitingApproval: "Se asteapta aprobarea",
  WaitingAdminApproval: "Contul dvs. așteaptă aprobarea administratorului. Odată aprobat, vă veți putea autentifica.",
  WrongPassword: "Parola gresita",
  WrongPasswordAlert: "Ai introdus parola incorect. Vă rugăm să încercați din nou.",
  UserNotFound: "Utilizator nu a fost găsit",
  UserNotFoundAlert: "Nu a fost găsit niciun utilizator pentru adresa de e-mail pe care ați introdus-o. Vă rugăm să vă înregistrați.",
  SameEmail: "Există deja un utilizator conectat la adresa de e-mail pe care ați introdus-o.",
  PasswordMatch: "parolele nu se potrivesc",
  PasswordMatchError: "Parolele pe care le-ați introdus nu se potrivesc între ele.",
  More: "Mai mult ",
  NewProducts: "Produse noi",
  PopularProducts: "Produse populare",
  AddToCart: "Adauga in coș",
  SendWhatsapp: "Contacteaza pe whatsupp",
  Pieces:"Bucati",
  gomlek: 'Camasa',
  mont: 'Palton',
  pantolon: 'Pantalon',
  bluz: 'Bluză',
  esofman: 'Trening',
  sweatshirt: 'Hanorac',
  tshirt: 'Tricou',
  elbise: 'Rochie',
  description:'Produsele noastre sunt 100% bumbac',
  ustgiyim:'Topuri',
  altgiyim:'Uzura de jos',
  quantityInCart:'Cantitate în coș ',
  pieces:'piese',
  all:'Toate',
  etek:'Fusta',
  Settings: "Setări",
  Sorry: "Scuze",
  NotLogin: "Nu puteți utiliza această funcție deoarece nu sunteți autentificat.",
  NavigateHome: "Continuați fără autentificare",
  OrderSended: "Comanda dvs. a fost livrată cu succes către vânzător. Vânzătorul vă va contacta la +90 5373673069.",
  SendOrder: "Cu excepția ferestrei pop-up",
  WorkingHour:"Programul nostru de lucru 8.30-19.00 UTC+3",
  priceDescription:"*Prețurile produselor noastre pot varia în funcție de cantitatea achiziționată, procesul de livrare și alte factori.*",
  OrderDetail:"Detalii comandă",
  Order:"Obține ofertă",
  ConfirmCart:"Confirmă coșul",
  CartEmpty:"Coșul dumneavoastră este gol, vă rugăm să adăugați produse!",
  OrderInfo:"Prețurile produselor pot varia în funcție de locația de livrare, cantitatea totală achiziționată și procesul de livrare. După plasarea comenzii, vă vom contacta în cel mai scurt timp posibil prin adresa de e-mail și numărul de telefon pentru a vă furniza informații.",
  Confirm:"Confirmă",
  Decline:"Renunță",
  SureOrder:"Doriți să confirmați coșul?",
  SurOrderAlt:"Dacă dați clic pe butonul 'Confirmă', comanda dvs. va fi transmisă vânzătorului și va fi procesată.",
  Delete:'Contul dvs. va fi șters definitiv. Sunteți sigur?',
  DeletePermanent:'Este posibil să trebuiască să vă înregistrați din nou.',
  OrderHistory: "Comenzile mele",
  new: "Nou",
  cancelled: "Anulat",
  pending: "În așteptare",
  completed: "Finalizat",
  Status: "Stare",
  OrderDate: "Data comenzii",
  TotalSeries: "Total serii",
  TotalPieces: "Total bucăți",
  DeletedPermanently: "Contul dvs. a fost șters definitiv."


};