export default tr ={
  Name:"Türkçe",
  ChangeLanguage:"Dili Değiştir",
  Hello:"Hoşgeldin! Ürünlerimiz 1. sınıf kumaşlardan üretilmiştir.",
  Country:"Ülke",
  Login:"Giriş Yap",
  Continue:"Devam Et",
  Email:"E-posta",
  Password:"Şifre",
  PasswordRt:"Şifre Tekrar",
  Register:"Kayıt Ol",
  NameSurname:"İsim-Soyisim",
  NavigateLogin:"Giriş ekranına dön",
  HomeScreen:"Ana Sayfa",
  Products:"Ürünler",
  MyBag:"Sepetim",
  Contact:"İletişim",
  Share:"Uygulamayı Paylaş",
  Logout:"Çıkış Yap",
  Subject:"Konu",
  Send:"Gönder",
  ContactUs:"Bizimle iletişime geçmek için aşağıdaki formu doldurup gönderebilirsiniz.",
  Error:"Hata!",
  EmailError:"Lütfen geçerli bir e-posta adresi girin.",
  FieldError:"Lütfen bütün boşlukları doldurun.",
  Ok:"Tamam",
  EmailProblem:"Girdiğiniz E-posta adresiyle ilgili kayıtlı bir sorun zaten var.",
  Congratulations:"Tebrikler!",
  CreateProblem:"Talebiniz başarıyla oluşturuldu, lütfen yanıt bekleyin :)",
  WaitingApproval:"Onay bekleniyor",
  WaitingAdminApproval:"Hesabınız yönetici onayını bekliyor. Onaylandıktan sonra giriş yapabileceksiniz.",
  WrongPassword:"Yanlış Şifre",
  WrongPasswordAlert:"Şifreyi yanlış girdiniz. Lütfen tekrar deneyin.",
  UserNotFound:"Kullanıcı Bulunamadı",
  UserNotFoundAlert:"Girdiğiniz e-posta adresine ait kullanıcı bulunamadı. Lütfen kaydolun.",
  SameEmail:"Girdiğiniz e-posta adresine bağlı bir kullanıcı zaten var.",
  PasswordMatch:"Parolalar uyuşmuyor",
  PasswordMatchError:"Girdiğiniz şifreler birbiriyle eşleşmiyor.",
  More:"Daha Fazla",
  NewProducts:"Yeni Ürünler",
  PopularProducts:"Popüler Ürünler",
  AddToCart:"Sepete Ekle",
  SendWhatsapp:"Whatsapp'tan Gönder",
  Pieces:"Parça",
  gomlek: 'Gömlek',
  mont:'Mont',
  pantolon:'Pantolon',
  bluz:'Bluz',
  esofman:'Eşofman',
  sweatshirt:'Sweatshirt',
  tshirt:'Tişört',
  elbise:'Elbise',
  ustgiyim:'Üst Giyim',
  altgiyim:'Alt Giyim',
  description:'Ürünlerimiz %100 pamuk.',
  quantityInCart:'Sepetteki Adet',
  pieces:'Parça',
  all:'Hepsi',
  etek:'Etek',
  Settings:'Ayarlar',
  Sorry:'Üzgünüz',
  NotLogin:'Giriş yapmadığınız için şu an bu özelliği kullanamazsınız.',
  NavigateHome:'Giriş yapmadan devam et',
  OrderSended:'Siparişiniz başarıyla satıcıya teslim edildi. Satıcı +90 5373673069 numaralı telefondan sizinle iletişime geçecektir.',
  Delete:'Hesabınız kalıcı olarak silinecektir emin misiniz?',
  DeletePermanent:'Tekrardan kayıt olmanız gerekebilir.',
  SendOrder:"Satın almak için gönder",
  WorkingHour:"Çalışma Saatlerimiz 8.30-19.00 UTC+3",
  priceDescription:"*Ürün fiyatlarımız aldığınız ürün adedi, kargolama süreci vb. bir çok etkene göre değişkenlik gösterebilmektedir.*",
  OrderDetail:"Sipariş Detayı",
  Order:"Teklif Al",
  ConfirmCart:"Sepeti Onayla",
  CartEmpty:"Sepetiniz boş lütfen ürün ekleyin!",
  OrderInfo:"Ürün fiyatları gönderilecek konum bilgisine, toplam satın alınan ürün adedine, kargolama süreçlerine göre değişkenlik gösterebilmektedir. Sipariş verdiğiniz taktirde en kısa sürede sizinle e-posta adresiniz ve gsm numaranız iletişime geçilip bilgilendirmeler sağlanacaktır.",
  Confirm:"Onayla",
  Decline:"Vazgeç",
  SureOrder:"Sepetini onaylamak ister misin?",
  SurOrderAlt:"Onayla butonuna tıklarsan siparişin satıcıya iletilecek ve temizlenecektir.",
  OrderHistory:"Siparişlerim",
  new:"Yeni",
  cancelled:"İptal Edildi",
  pending:"Beklemede",
  completed:"Tamamlandı",
  Status:"Durum",
  OrderDate:"Sipariş Tarihi",
  TotalSeries:"Toplam Seri Adedi",
  TotalPieces:"Toplam Adet",
  DeletedPermanently:"Hesabınız Kalıcı Olarak Silinmiştir.",
};